version: '2'
services:
  redis_db:
    image: redis:5.0
    restart: always
    volumes:
      - /var/mount/analytic/redis/db:/data/db
      - /var/mount/analytic/redis/log/:/var/log/
    ports:
      - "127.0.0.1:6379:6379"
  postgre_db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: 1234QAZWSx
      POSTGRES_USER: admin
    volumes:
      - /var/mount/analytic/postgre_db/data:/var/lib/postgresql/data
      - /var/mount/analytic/postgre_db/log:/var/log/
    ports:
      - "5432:5432"
  django:
    build: ./
    environment:
     - POSTGRES_DB_NAME=analytic_db
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=1234QAZWSx
     - POSTGRES_HOST=postgre_db
    ports:
    - "10301:80"
    depends_on:
      - postgre_db
      - redis_db
  celery:
    build:
      context: .
      dockerfile: CeleryDockerfile
    environment:
      - POSTGRES_DB_NAME=vysotsky_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234QAZWSx
      - POSTGRES_HOST=postgre_db
    depends_on:
      - postgre_db
      - redis_db
      - django
  celery-beat:
    build:
      context: .
      dockerfile: CeleryBeatDockerfile
    environment:
      - POSTGRES_DB_NAME=analytic_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234QAZWSx
      - POSTGRES_HOST=postgre_db
    depends_on:
      - postgre_db
      - redis_db
      - django